### ISSUE TITLE
Google Play Services, Audience Network, Game Analytics and Unity's IAP in a single project - Multi Dex error on build Android

### ISSUE THREAD

**Issue by pranavt07** [googlesamples/unity-jar-resolver#152]
I am working on a project which has the following APIs - 
Google Play Services
Audience Network (Facebook)
Game Analytics
Unity In App Purchasing.

It is giving me the issue given in the image when I try to build for Android :
<img width="794" alt="screen shot 2018-09-22 at 5 44 15 pm" src="https://user-images.githubusercontent.com/43460823/45917165-267b0f80-be8f-11e8-8461-7d78f2ec1c1a.png">

I tried using the Unity Jar Resolver to fix this issue but it keeps giving me the same issue. 

I had also contacted Game Analytics who told me the following - 

shows that two different versions of play services are being used at this moment in your project; 11.6.2 and 15.0.1. In order to use GA plugin successfully alongside other plug in's, the other plugin must match our version of 15.0.1. You can contact the makers of the other plugin, and request for the plugin to updated to this version.

It would be great if anyone could find a solution for this.

**Comment by stewartmiles** [comment]
@pranavt07 the Android Resolve does not remove duplicate Android libraries from your project.  If you want to migrate everything to the Android Resolver:

- Remove (i.e delete) all Android libraries from the plugins you're importing.
- Add references to the Android libraries using the Android Resolver, see [here](https://github.com/googlesamples/unity-jar-resolver#android-resolver-usage).

As the Game Analytics folks mentioned, you should ask plugin developers to use the Android Resolver instead of redistributing libraries like Google Play Services that could be duplicated across multiple plugins.

**Comment by pranavt07** [comment]
Hey, so I tried that but somehow it hasn't worked out. I could be doing it incorrectly. But, I am still getting the same issue. Apart from Game Analytics, the only other thing that could give a major issue is Facebook Audience Network. 

If there are any alternative ways for this, kindly let me know for the same.

**Comment by stewartmiles** [comment]
I recommend starting with a simple project and adding each plugin one at a time to narrow down the problematic plugin.  In addition, you can turn on verbose logging in the Android Resolver settings menu to see which .xml files or source files are adding dependencies via the Android Resolver.

**Comment by stewartmiles** [comment]
@pranavt07 since I haven't heard from you I'm going to close this out.
