### ISSUE TITLE
Calling Resolver in Batch mode

### ISSUE THREAD

**Issue by vtimejc** [googlesamples/unity-jar-resolver#153]
Is there a reliable way to call the resolver in batch mode e.g. when running automated builds?

I end up with no libraries and an empty < files / > when I try calling GooglePlayServices.PlayServicesResolver.MenuForceResolve(); from our batch-mode build script.

We have various configurations we'd like to switch between and it'd be great if we could also auto-update dependencies hassle free.

**Comment by stewartmiles** [comment]
You need to use the synchronous resolve method otherwise when you check for the libraries  after calling MenuForceResolve() the process will still be running.

Here's the code:
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/PlayServicesResolver.cs#L1225

Here's the test case that calls it:
https://github.com/googlesamples/unity-jar-resolver/blob/36ada374c8557f8237a6d5b01964b91cdebf4c01/source/PlayServicesResolver/test/resolve_async/Assets/PlayServicesResolver/Editor/TestResolveAsync.cs#L542
