### ISSUE TITLE
Please Help, Resolver OK but build error

### ISSUE THREAD

**Issue by takaaptech** [googlesamples/unity-jar-resolver#166]
Hi! @stewartmiles 
Please help me to find out why this error, when I run force resolver, It resolver ok
But when we build the game, It error, with the log file attached
I need your help to find out how to resolve it. So I will try to find my self to correct it next time
Thank so much!

Please search for Note: there were 17 duplicate class definitions.
[log.txt](https://github.com/googlesamples/unity-jar-resolver/files/2560628/log.txt)

I use version 1.2.95 to resolve Firebase 5.4.1 and some other libs

**Comment by stewartmiles** [comment]
@takaaptech on this repo we're cool with debugging issues with the resolver but this looks very specific to your project.  I recommend making a minimal project and importing each plugin component that you're using one by one to figure out which one is adding duplicate Android libraries.  If the plugin vendor isn't using the Android Resolver (i.e they're redistributing JARs / AARs directly to their plugin) you may want to nudge them to use the Android Resolver plugin so that they can integrate with other Unity plugins.  If it looks like a Firebase problem, goto https://firebase.google.com/support and submit a ticket.

If you want to figure this out in your project you could unzip all AAR / JAR files (they're just zip files) and search for duplicate class filenames.  For example, in your attached log there is the line:

```Warning: Exception while processing task java.io.IOException: Can't write [E:\OneSoftGames\Projects\Wing Of Justice - IronSource 2 -Unity 2018\Temp\gradleOut\build\intermediates\transforms\proguard\release\0.jar] (Can't read [C:\Users\ADmin\.gradle\caches\transforms-1\files-1.1\com.google.android.gms.play-services-measurement-sdk-api-16.0.2.aar\3db860b1afe4c7f5e79d5218f2ad183f\jars\classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:com/google/android/gms/internal/measurement/zzdz.class]))```

So you could unpack all JAR / AAR files and then unzip the classes.jar files to search for the path `com/google/android/gms/internal/measurement/zzdz.class`.

**Comment by takaaptech** [comment]
@stewartmilesI appreciate your support! I am very scaring when reading very long log file like that.
Back to this issue, somehow we using old play services ads in GoogleMobileAdsDependencies.xml
```
<androidPackage spec="com.google.android.gms:play-services-ads:11.2.2">
```

So I change it to 16.0.0 and everything works well now.
I really want to learn to read the error log to find out why this happens, so we can point out where is the error. Or maybe our plugin can show some hint about that.
I wonder when the unity-jar-resolver resolve it ok but we have still duplicate class between aar files, is there some way to check it?
Thank you so much @stewartmiles

**Comment by takaaptech** [comment]
@stewartmiles That something I hope unity-jar-resolver can do. I am so sorry I do not have enough background for contributing pull request to our plugin (Mainly because of complicated in grade system, firebase, and gms nightmare).
Thank so much for your support!
