### ISSUE TITLE
A problem occurred starting process 'command 'C:\Program Files\Unity\Editor''

### ISSUE THREAD

**Issue by jackflyer** [googlesamples/unity-jar-resolver#178]
Windows -8.1, Unity 5.6
When try to build from latest source this error occurred.
`A problem occurred starting process 'command 'C:\Program Files\Unity\Editor''`
 Path for Unity.exe on windows is actually C:\Program Files\Unity\Editor\Unity.exe , path shown in error is not executable path.

**Comment by stewartmiles** [comment]
Since Unity can be installed anywhere on the machine, the build script searches some known locations including the default install path https://github.com/googlesamples/unity-jar-resolver/blob/master/build.gradle#L39

If this logic isn't working on your machine you can change UNITY_EXE in gradle.properties to point to the correct location.

**Comment by jackflyer** [comment]
Yes, It was that.
