### ISSUE TITLE
Resolve now taking 35 minutes !

### ISSUE THREAD

**Issue by apautrot** [googlesamples/unity-jar-resolver#185]
Hi,
I'm working on a Unity project. I'm integrating AdMob with various Mediation plug-ins.

With the integration of MoPub Mediation Plug-in, which adds its own Dependencies.xml file, the Gradle build time goes from 49s to 35m 16s.

Is it something to expect ? Is that a 'normal' behavior ?

I'm really worried about that result...
Can you please advice me on this ?

**Comment by apautrot** [comment]
Just added a new dependency (Tapjoy Mediation for Admob), now I'm at 37m 19s.

**Comment by stewartmiles** [comment]
@apautrot certainly doesn't sound like normal behavior, especially since once a successful resolve occurs the results are stored in the project.  If you're not checking in the results of the resolution then it will take a long time to search the graph of dependencies to find a set that works.

Really if you see a resolve take a long time, check the console output and see what it did to your dependencies to fix them and then apply those changes to the *Dependencies.xml files in the project.

**Comment by apautrot** [comment]
Hi Stewart,
Do you have any documentation on doing this ? The console output I have at end of resolve is

> Some conflicting dependencies were found.
The following dependency versions were modified:
com.facebook.android:audience-network-sdk:5.1.0 --> com.facebook.android:audience-network-sdk:+
com.google.android.ads:mediation-test-suite:0.9.2 --> com.google.android.ads:mediation-test-suite:+
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
com.google.firebase:firebase-analytics:16.0.5 --> com.google.firebase:firebase-analytics:+
com.google.firebase:firebase-common:16.0.4 --> com.google.firebase:firebase-common:+
com.google.firebase:firebase-core:16.0.5 --> com.google.firebase:firebase-core:+
com.mopub:mopub-sdk:5.4.1 --> com.mopub:mopub-sdk:+
com.tapjoy:tapjoy-android-sdk:12.2.0 --> com.tapjoy:tapjoy-android-sdk:+

Also, by 'checking in the results' do you mean saving ProjectSettings\AndroidResolverDependencies.xml that have been updated (alongside with all .arr/.jar files updates) ? Because I doing that, I'm committing all file changes after a resolution.

Each time I'm doing a resolve, all files (.arr/.jar) are deleted first, then the resolve does its job. Could this be an unwanted behavior ?

**Comment by stewartmiles** [comment]
@apautrot if conflicting dependencies are found, the resolver will loosen the version spec for packages progressively until it can find a set that work together.  In your case, it looks like it just ended up grabbing the head version of each package (e.g foo.bar:bish.bash:+ would grab the latest foo.bar:bish.bash).

The version of each package is grabbed is encoded in the filename of the package dropped into `Assets/Plugins/Android` e.g `Assets/Plugins/Android/com.google.firebase.firebase-common-16.0.4` is version 16.0.4 of `com.google.firebase:firebase-common`.  For each component you *could* go update each *Dependencies.xml with the versions the resolver downloaded to keep things pinned for future resolutions.  I guess it would be nice to have a feature to apply the changes back to the project.

If you've checked in `ProjectSettings\AndroidResolverDependencies.xml` and the `.aar` / `.jar` files along with the produced folders in `Assets/Plugins/Android` resolution shouldn't occur again unless you force the process.  If you're still seeing auto-resolution happening you should enable verbose logging and it will tell you what is expected and what is missing in the logs.

**Comment by apautrot** [comment]
Thank you for this explanation. I'll give a try and get back in case of an issue, if any.

The resolution is instantaneous, as expected, when already successfully completed. I have disabled auto-resolution.

**Comment by stewartmiles** [comment]
@apautrot that is an insane amount of time to resolve the dependencies in your project.  Are you on dial-up? :)   Each androidPackage scope is what you would need to update in the *Dependencies.xml files.  AndroidResolverDependencies.xml is simple a cache of what is stored in the project so that the resolver can see whether any files in the project or the configuration has changed since the last time resolution ran.
