### ISSUE TITLE
No Google.VersionHandlerImpl DLL found to bootstrap

### ISSUE THREAD

**Issue by anesask** [googlesamples/unity-jar-resolver#222]
`No Google.VersionHandlerImpl DLL found to bootstrap
UnityEngine.Debug:LogWarning(Object)
Google.VersionHandler:BootStrap() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandler/src/VersionHandler.cs:156)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
`

I have tried previously installed Android SDK and NDK and same installed with Unity via HUB, but still throwing this error...

**Comment by stewartmiles** [comment]
@anesask sounds like the plugin was broken on import.

The error is coming from:
https://github.com/googlesamples/unity-jar-resolver/blob/e71269b2b7391efa72fe9675f706376f11a1e123/source/VersionHandler/src/VersionHandler.cs#L156

This is because the Google.VersionHandlerImpl dll can't be found in the project
https://github.com/googlesamples/unity-jar-resolver/blob/e71269b2b7391efa72fe9675f706376f11a1e123/source/VersionHandler/src/VersionHandler.cs#L150

Perhaps the `gvh` asset label was lost on import?

**Comment by stewartmiles** [comment]
I'll assume your issue was fixed by reimporting the plugin.  Let us know if you still have a problem.
