### ISSUE TITLE
PlayServicesResolver 1.2.121 - iOS dll is broken

### ISSUE THREAD

**Issue by huran438** [googlesamples/unity-jar-resolver#247]
iOS dll cant load into unity3d 2019.1.8f1

**Comment by stewartmiles** [comment]
@huran438 what is broken exactly?  Could you share the error(s) you're seeing?

**Comment by bdominguez** [comment]
Same problem here:

Unloading broken assembly Assets/PlayServicesResolver/Editor/Google.IOSResolver_v1.2.121.0.dll, this assembly can cause crashes in the runtime

**Comment by stewartmiles** [comment]
That is spuriously reported by Unity but I'm fairly sure it will eventually load it anyway, are you sure it isn't loaded?  Can you see the menu `Assets > Play Services Resolver > iOS Resolver > Settings`?  If so, it's loaded and you can ignore the message from Unity.

https://issuetracker.unity3d.com/issues/unloading-broken-assembly-error-message-provides-insufficient-information

There are a load of bug reports about this sort of thing across a load of plugins and they're all caused by Unity throwing an error before compilation and plugin configuration is complete.

**Comment by bdominguez** [comment]
@stewartmiles This error appears every time I compile not the first time you import the "*.unitypackage".

Personally when I have found that error is usually because of missing dependencies or incorrect target (.NET 3.5 vs .NET 4.x).

It's a real error, ignoring it is not an option because every time you recompile you get a new error in the console.

**Comment by stewartmiles** [comment]
Any chance you have the Version Handler's version management disabled?

If not, perhaps your plugin import got into a bad state.  Try deleting Assets/PlayServicesResolver and reimporting the plugin.

**Comment by bdominguez** [comment]
@stewartmiles I have created a fresh project and I have the same problem. Repro steps:

1. Create new project.
2. Import unity package.
3. Compilation finishes and I got an error on the console.

**Comment by stewartmiles** [comment]
@bdominguez ok I've reproduce it, yeah it's when the iOS extension isn't installed in Unity the iOS DLL now fails to load in Unity 2019 :/ . This does not happen in earlier versions of Unity.

**Comment by stewartmiles** [comment]
Workaround applied in https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.122

**Comment by bdovaz** [comment]
@stewartmiles Thanks!!

**Comment by bdominguez** [comment]
https://github.com/googlesamples/unity-jar-resolver/issues/247
