### ISSUE TITLE
Version lock possibly not working

### ISSUE THREAD

**Issue by spium** [googlesamples/unity-jar-resolver#249]
Hi,
I'm having trouble with the resolver, though it's possible I misunderstand how it works.
I'm using the latest 1.2.122 version.
I've specified the following dependency:
`com.google.android.gms:play-services-ads:[16.7.1]`
If I understand correctly, the [] should make sure that exact version is being used. However after running the resolver I end up with play-services-ads:17.2.1 due to some other plugin's dependencies.
Is it possible to force using that specific version?

Cheers,
Giovanni

**Comment by a-maurice** [comment]
Hi @spium 

Unfortunately, there isn't a way to lock to a specific version like you are requesting, because there wouldn't be a way to resolve conflicts should multiple plugins lock to different versions.  The one way to accomplish locking to a particular version would be to update all the *Dependencies.xml files that refer to newer versions, and set those to an older version as well.

If I can ask, why do you need to force a specific older version?

**Comment by spium** [comment]
Hi, I'm using an early access version of Google Mobile Ads which needs custom play services libraries, which are at that version. I managed to solve by downgrading the other plugins as you suggested.
Thanks!

**Comment by a-maurice** [comment]
Great, thanks for letting us know.
