### ISSUE TITLE
Removing pods

### ISSUE THREAD

**Issue by kjakm** [googlesamples/unity-jar-resolver#271]
Apologies for opening an issue for a question but I have searched the source files + tried getting assistance elsewhere but haven't found a solution.

I am using:

`        Type iOSResolver = Google.VersionHandler.FindClass("Google.IOSResolver", "Google.IOSResolver");

        Google.VersionHandler.InvokeStaticMethod(
            iOSResolver, "AddPod",
            new object[] { podName },
            namedArgs: namedArgs
        );
`

Via checkboxes I let users add various pods (and I call the above code each time they enable one). Obviously they can later uncheck these pods. I cannot find any method to 'RemovePod'. Is this possible?

**Comment by stewartmiles** [comment]
Rather than using the programmatic API it's probably better to generate an XML file with the included pods for the project as the API isn't really stable and as you can see requires reflection to use.  Also, there isn't a public API for clearing the set of iOS pods added to the plugin, all you can do is reload the editor plugin via [AssetDatabase.Refresh](https://docs.unity3d.com/ScriptReference/AssetDatabase.Refresh.html) which is really slow.  The XML dependencies get reloaded at build time here https://github.com/googlesamples/unity-jar-resolver/blob/a00f7d0e6b8c0cb64bb6b605ac6f1fe1c62985cb/source/IOSResolver/src/IOSResolver.cs#L2292 so if you generate a *Dependencies.xml file when the set of components selected change that should always work.

**Comment by stewartmiles** [comment]
@kjakm did generating `*Dependencies.xml` files work for you?

**Comment by kjakm** [comment]
@stewartmiles sorry I didn't get back to you. Using XML to manage the dependencies worked great, thanks!
