### ISSUE TITLE
Question : other library

### ISSUE THREAD

**Issue by grosalex** [googlesamples/unity-jar-resolver#28]
Is there a way to use this for other library like exoplayer or https://github.com/koush/ion or picasso ? So we wouldn't have to get the jar of those?

Regards,

**Comment by stewartmiles** [comment]
We don't currently have support for downloading aars from maven repos, it sure would be nice.  If you want to take a stab at it we are happy to accept pull requests :)

**Comment by martino2k6** [comment]
Has anyone started working on this? It's a feature that would be useful to me, so if no one has started on it I would be happy to give it a try.

**Comment by stewartmiles** [comment]
We've started working on support for downloading aars from maven repos using gradle to do the heavy lifting.  It's all pretty experimental at the moment though.  We would still quite like an option to download AARs via the existing eccentric dependency management setup we have in place, if you want to give it a try that would be great.

**Comment by martino2k6** [comment]
Do you mean that you've used Gradle in a separate project to download dependencies from Maven or that it was integrated into the Unity Jar Resolver?

We have something [here](https://github.com/deltaDNA/unity-sdk/tree/master/Assets/DeltaDNAAds/Editor/Android) that we've used on our side where the Gradle project is used by a Unity Editor script to pull down some AARs, however we would prefer a singular way of pulling the libraries down. As well as a method which other plugin makers and/or game devs would be more likely to use to avoid conflicts between libraries being provided from different sources.

If the aim is to provide similar dependency management behaviour to Gradle (which I'm fairly sure is the case), then using Gradle underneath seems like a sensible approach to me compared to re-implementing similar logic outside of it.

**Comment by stewartmiles** [comment]
We're generating a Gradle project inside the Jar Resolver for all of the declared dependencies, partially building it to apply transformations like proguard then taking the partially built artifacts and generating an eclipse / ant style project to be consumed by Unity's legacy build system.

As I mentioned it's early days and the code is trickling in to get this working with the primary objective of having a path to proguard Android Java components in Unity projects.

Once we have the first piece in place it would be great to tear out JarResolverLib and all the horrendous logic for dependency management in there with the Gradle project generation in order to pull down the dependencies.

**Comment by martino2k6** [comment]
In light of the new details we have decided not to proceed with making any changes to the project, as it seems like you've already got something underway that will either do what would be useful to us or at least provide a foundation for it. Thanks and keep up the good work :)

**Comment by stewartmiles** [comment]
Yeah they're basically dupes at this point.  We have a patch lined up for this, hang tight.

**Comment by stewartmiles** [comment]
This should be supported as of bd2258481db7130a4f6ae7b1969acf0fb488733e
