### ISSUE TITLE
Build machines occasionally Reset Android Resolver settings to default.

### ISSUE THREAD

**Issue by CriticalForce** [googlesamples/unity-jar-resolver#301]
Unity editor version:  2018.4.12f1
Play Services Resolver version: 1.2.132.0

Features in Play Services Resolver in use:
Android Resolver, iOS Resolver, VersionHandler

Plugins SDK in use:
GPG 0.10.06
FireBase 6.6.0
FB 7.18.0
AdMob (via IronSource)

Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Mac

Platform you are targeting (iOS, Android, and/or desktop): 
Android

Scripting Runtime (Mono, and/or IL2CPP):
IL2CPP

### Repro:
Once we trigger a pipeline build in batch mode the build occasionally defaults the settings and causes build issues due to Patch MainTemplate.gradle being changed.
We noticed that on a (first) clean import of the repo (on a Mac) the Android Resolver settings were defaulted as well.
Repro rate is ~20%

On a repro case, this initially happens:
![image](https://user-images.githubusercontent.com/11941373/69418629-be8ab800-0d23-11ea-81c5-544b283fbc76.png)

**Comment by draber-assf** [comment]
Want to call out that we're experiencing this with a 100% repro rate.

Unity editor version: 2017.4.31f1
Play Services Resolver version: 1.2.131.0

Features in Play Services Resolver in use:
Android Resolver, iOS Resolver, VersionHandler

Plugins SDK in use:
GPG 0.10.06
FireBase 6.0.0
FB 7.17.2
AdMob (via IronSource)
HyperMX 5.0.1
Some other stuff I'm probably forgetting.

Platform you are using the Unity editor on (Mac, Windows, or Linux):
Mac

Platform you are targeting (iOS, Android, and/or desktop):
Android

Scripting Runtime (Mono, and/or IL2CPP):
IL2CPP

**Comment by draber-assf** [comment]
> So far, we believe the resolver is blowing away gvhprojectsettings.xml on initial import in Unity. The Save function appears to be called during this point, so we're attempting to call Load before it

> So far, we believe the resolver is blowing away gvhprojectsettings.xml on initial import in Unity. The Save function appears to be called during this point, so we're attempting to call Load before it

More info on this: The Save call is happening during class load, which means any change we make needs to be in the plugin code itself since our class Unity side isn't loaded before Save is called.  We're now attempting to make the change in the plugin and recompile.  We'd certainly classify the fix (if it even works) as a hack and would appreciate guidance on the right way to do it.

**Comment by draber-assf** [comment]
> > So far, we believe the resolver is blowing away gvhprojectsettings.xml on initial import in Unity. The Save function appears to be called during this point, so we're attempting to call Load before it
> 
> More info on this: The Save call is happening during class load, which means any change we make needs to be in the plugin code itself since our class Unity side isn't loaded before Save is called. We're now attempting to make the change in the plugin and recompile. We'd certainly classify the fix (if it even works) as a hack and would appreciate guidance on the right way to do it.

Ok.  Hopefully last comment here.  We believe we've found the culprit.

Roughly, the problem occurs because Unity is running in batch mode.  The offending line that was added is here in VersionHandlerImpl.cs: [VerboseLoggingEnabled = VerboseLoggingEnabled;](https://github.com/googlesamples/unity-jar-resolver/blob/65cf5b55599c8c9ad2b094e8bcae4f3b27e051af/source/VersionHandlerImpl/src/VersionHandlerImpl.cs#L1535)

In batch mode, the getter for this is short-circuited.  When not in batch mode, the getter normally calls settings.GetBool, which in turn calls [LoadIfEmpty();](https://github.com/googlesamples/unity-jar-resolver/blob/65cf5b55599c8c9ad2b094e8bcae4f3b27e051af/source/VersionHandlerImpl/src/ProjectSettings.cs#L601) on the ProjectSettings object.

Following the GetBool (or short-circuit), we call the setter which calls SetBool, which calls [Save();](https://github.com/googlesamples/unity-jar-resolver/blob/65cf5b55599c8c9ad2b094e8bcae4f3b27e051af/source/VersionHandlerImpl/src/ProjectSettings.cs#L800).  When in batch mode we haven't Loaded ProjectSettings yet, so we effectively wipe all existing keys in order to write out a key to the same value.

The quick fix here (that we're attempting) is to modify [VerboseLoggingEnabled.get](https://github.com/googlesamples/unity-jar-resolver/blob/65cf5b55599c8c9ad2b094e8bcae4f3b27e051af/source/VersionHandlerImpl/src/VersionHandlerImpl.cs#L1682) and flip the or statement (basically, force it to call GetBool rather than short-circuiting in batch mode).  The proper fix is probably to force a load on ProjectSettings before this call, but I'll leave that to the main plugin devs to say.

**Comment by draber-assf** [comment]
Confirmed.  The above solution fixes the issue.

**Comment by MagicMiikka** [comment]
Thanks @draber-assf I will await an official release for this issues.
We downgraded back to 1.2.130 and the issue indeed disappeared.

**Comment by stewartmiles** [comment]
Thanks for tracking this down, @draber-assf you're absolutely right the bug here appears to be in the ProjectSettings which isn't loading the settings before setting and writing updated settings.
