### ISSUE TITLE
 PlayServicesResolver replaces scenes asset bundles hashes

### ISSUE THREAD

**Issue by Incont** [googlesamples/unity-jar-resolver#315]
### Please fill in the following fields:
Unity editor version: 2019.2.9
Play Services Resolver version: 1.2.133.0
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac, Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I added Firebase to my project, and got a major problem - all scenes asset bundles have new hashes, but the files weren't modified. It means that users will reload all scenes (900mb for my project). It is very bad user experience.
I researched the problem and found the reason.
Play Services Resolver contains an internal class GooglePlayServices.PlayServicesPreBuild that uses the UnityEditor.Callbacks.PostProcessScene attribute for showing warning message. I checked in the test project, adding and deleting the PostProcessScene attribute in code affects scenes asset bundles hashes.
You should use IPreprocessBuild.OnPreprocessBuild (for unity 2017) and IPreprocessBuildWithReport.OnPreprocessBuild (for new unity) intead of the PostProcessScene atribute.
Please fix it.
https://github.com/Incont/UnityTestApp is test project for building scene asset bundle.
Also, you can add PlayServicesResolver and test with it.
### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by Incont** [comment]
Also PlayServicesResolver.OnPostProcessScene has PostProcessScene atribute.

**Comment by paulinon** [comment]
Hi @Incont you can try making use version 1.2.135.0. On my end, the hash values are the same when I did your steps to reproduce your issue.

**Comment by Incont** [comment]
I checked 1.2.135.0.
Steps: 
1. Built scene bundle without PlayServiceResolver. Result: testscene_476ef117e516dc14b5ba4791996f2036
2. Built scene bundle with PlayServiceResolver 1.2.135.0 Result: testscene_c83cc3af8eac13fec72e5a99b08ae661
Bundle hash was udated before adding PlayServiceResolver 1.2.135.0
This is expected behavior, becouse PlayServiceResolver 1.2.135.0 contains 2 place in code with PostProcessScene atribute.

**Comment by Incont** [comment]
The bug https://github.com/firebase/quickstart-unity/issues/561 has the same reason.

**Comment by paulinon** [comment]
Hi @Incont, I was able to reproduce the issue with your results. I've filed an internal bug report for this. I'm not able to share any timelines for the fix, so I'll leave this open.

**Comment by stewartmiles** [comment]
@Incont we're using an API that is still supported by Unity https://docs.unity3d.com/ScriptReference/Callbacks.PostProcessSceneAttribute.html so the fact it changes scene bundle GUIDs when running the post processing step sounds like a bug in Unity to me.  Have you reported the issue to Unity?

We can't really use IPreprocessBuild.OnPreprocessBuild or IPreprocessBuildWithReport.OnPreprocessBuild and support all Unity versions we need to support (back to 5.3).

That said, I pulled your test project https://github.com/Incont/UnityTestApp and after doing some rough checking to see whether it would own me, ran through the outlined process.

When uncommenting [this line](https://github.com/Incont/UnityTestApp/blob/2721367926a53ceca26edb76d56d3369475e67d8/Assets/Editor/BuildAB.cs#L19) indeed the asset bundle hash changes.  However, if you leave it uncommented and continue to build asset bundles, the hash remains the same.

Here's my output of diff when building with your project, of course the manifests are different but the hash between the assets are the same.

```
$ diff -r AssetBundles_06-03-2020-15-{02,03}*
Only in AssetBundles_06-03-2020-15-02-55: AssetBundles_06-03-2020-15-02-55
Only in AssetBundles_06-03-2020-15-02-55: AssetBundles_06-03-2020-15-02-55.manifest
Only in AssetBundles_06-03-2020-15-03-05: AssetBundles_06-03-2020-15-03-05
Only in AssetBundles_06-03-2020-15-03-05: AssetBundles_06-03-2020-15-03-05.manifest
$ diff -r AssetBundles_06-03-2020-15-{02,04}*
Only in AssetBundles_06-03-2020-15-02-55: AssetBundles_06-03-2020-15-02-55
Only in AssetBundles_06-03-2020-15-02-55: AssetBundles_06-03-2020-15-02-55.manifest
Only in AssetBundles_06-03-2020-15-04-01: AssetBundles_06-03-2020-15-04-01
Only in AssetBundles_06-03-2020-15-04-01: AssetBundles_06-03-2020-15-04-01.manifest
$ diff AssetBundles_06-03-2020-15-02-55/AssetBundles_06-03-2020-15-02-55.manifest AssetBundles_06-03-2020-15-03-05/AssetBundles_06-03-2020-15-03-05.manifest
# nothing
``` 

After closing and reopening Unity with the project and rebuilding the bundle again, same thing...

```
$ diff -r AssetBundles_06-03-2020-15-04-01 AssetBundles_06-03-2020-15-09-14
Only in AssetBundles_06-03-2020-15-04-01: AssetBundles_06-03-2020-15-04-01
Only in AssetBundles_06-03-2020-15-04-01: AssetBundles_06-03-2020-15-04-01.manifest
Only in AssetBundles_06-03-2020-15-09-14: AssetBundles_06-03-2020-15-09-14
Only in AssetBundles_06-03-2020-15-09-14: AssetBundles_06-03-2020-15-09-14.manifest
```

After adding some code to `EmptyMethod`, no change..

```
$ diff -r AssetBundles_06-03-2020-15-09-14 AssetBundles_06-03-2020-15-11-14
Only in AssetBundles_06-03-2020-15-09-14: AssetBundles_06-03-2020-15-09-14
Only in AssetBundles_06-03-2020-15-09-14: AssetBundles_06-03-2020-15-09-14.manifest
Only in AssetBundles_06-03-2020-15-11-14: AssetBundles_06-03-2020-15-11-14
Only in AssetBundles_06-03-2020-15-11-14: AssetBundles_06-03-2020-15-11-14.manifest
```

So while adding methods with PostProcessSceneAttribute indeed appears to change the hash for asset bundle builds which sounds like a Unity bug they're unlike to fix since asset since it's [deprecated](https://docs.unity3d.com/Manual/AssetBundles-Building.html) I don't see a reasonable workaround for us to apply at the moment.

FYI https://forum.unity.com/threads/how-is-asset-bundle-crc-and-hash-created.352312/ suggests this is a mess already.
