### ISSUE TITLE
Cannot install gem in Unity

### ISSUE THREAD

**Issue by linhtn94** [googlesamples/unity-jar-resolver#321]
### Please fill in the following fields:
Unity editor version: 2018.2.21f1
Play Services Resolver version: 1.2.135
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): iOS Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Facebook, LineSDK
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac
Platform you are targeting (iOS, Android, and/or desktop):  iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.

### Please answer the following, if applicable:
100%

**Comment by paulinon** [comment]
Hi @linhtn94, this error message seems rather unusual. I found this [community post](https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma) which could help you with your issue. 

If this doesn't work, please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project as well as the steps you've done before encountering this issue, so that I can try to reproduce this on my end.
