### ISSUE TITLE
Recommended "Resolution" for Complex Projects (Android X)

### ISSUE THREAD

**Issue by thomasjohnwolfe** [googlesamples/unity-jar-resolver#338]
### Unity editor version: 
2018.4.2f1

###External Dependency Manager version: 
Current: 1.2.105.0
Attempted Upgrade: 1.2.137.0

###Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.):
We use the *Dependencies.xml files to define iOS and (newer) Android SDK dependencies.
Most Unity plugins seem to be using this now and we've converted our internal solutions to also use these files.

###Plugins SDK in use:
Adjust - 4.13
Admob - 4.2.1
Admob Mediation, AppLovin, Facebook Audience Network, IronSource, UnityAds, Vungle
Apple ID "Lupidan Sign In With Apple“
BuildPipeline(DotsInternal)
Braze - 1.21.2 => Relies on Custom JAR (and our own Deep-link solution) that extends AppboyUnityPlayerActivity extends UnityPlayerActivity
Facebook => Divergent(2 unity SDKS) unity-7.11.1 (Android)unity-7.18.1 (iOS)
Firebase - Unity - 5.3.0
Google Play Games - 9.50
Localytics - 2.5 (this is old!)
SafeDK 
Sentry - (custom plugin that wraps native)
Unity IAP - 1.22.0

### Platforms you are using the Unity editor:
Mac/Windows (mostly Macs)

### Platforms you are targeting: 
Android / iOS 

###Scripting Runtime:
IL2CPP

### Please describe the issue here:
We haven't been able to use this plug-in as intended to "resolve" for over a year now due to the complexity/history of our project.  This plug-in was intended as a one-time solution to "resolve" dependencies. We are large game studio with complex SDK management and custom CI. Our game has been live for roughly 6 years.

Is there any sort of configuration you would recommend where we can run "resolve" without running any sort of custom processing, reverting of files, or guess work?
I’d like to work with this plug-in and not against it. It is a great tool for a newer setup or a project with less SDKS and less custom solutions. It works well for other (newer) projects in our studio.

Currently when after we use the plugin to "resolve" Android dependencies we have to do one or more of the following:
- Commit the libraries we need and then revert the rest (quite often this happens with extremely time consuming amounts of trial and error and swapping in and out versions of Play Services Resolver)
- Avoid the plugin in directly and download the files we need from Maven directly.
- Run the resolver 2x for production and dev bundle IDs and then make custom preprocessor scripts (for Firebase that copy the AARs in and out of Unity project)
- There are usually a large amount of "dex" errors (lately) which seem harder to resolve by using this plug-in, than it was 4 years ago without it.

Now with newer SDKs moving towards Android X, problems with this plugin are even worse (scarier) and it seems we are about to reach a tipping point where half our plug-ins want to use Android X libraries and old ones we will have to remove. We are trying to avoid updating 3+ SDKs at a time to fix these issues (as its very risky and our game is live)

Here is a link to a watered down log (trimmed for security reasons) of tests I have performed trying to make builds over the past week when exploring this issue.
https://dots.quip.com/uGq0Ajvzs7LM/Android-X-Exploration-Play-Services-Resolver

I anticipate this might be a duplicate issue. But we have been doing research on our plan for supporting Android X and I have yet to make a build that works. So please feel free to point me in the right direction!

Thanks!
Thomas Wolfe

### What's the issue repro rate?
95% of the time we do an SDK update for Android, we run into large scale issues that can’t seem to be fully resolved with this plugin the way it was intended.

**Comment by chkuang-g** [comment]
Hi @thomasjohnwolfe 

Without diving too deep into your configuration, here is my understanding:

- Among all plugin your project use, `Admob`, `Facebook`, `Firebase` and `Google Play Game` is using AndroidResolver to resolve Android dependencies.
- The latest EDM would prompt to utilize Jetifier to migrate libraries for AndroidX https://github.com/googlesamples/unity-jar-resolver/commit/7f438bac0f1ffed421788c6e84ef679d573adba1
   https://developer.android.com/jetpack/androidx#using_androidx
   You can also find the setting to enable it in `Assets > External Dependency Manager > Android Resolver > Setting`
- If you have additional `.aar` or `.jar` which you like to resolve along with those required by other plugins, I think you can define your own *Dependencies.xml and AndroidResolver will take that into consideration during resolution.
- If you still have trouble to build Android, you can use custom gradle template.  More information:
   https://github.com/googlesamples/unity-jar-resolver/issues/145#issuecomment-509958657
   https://docs.unity3d.com/Manual/android-gradle-overview.html

Hope this helps.

**Comment by chkuang-g** [comment]
There is a similar issue #349

As mentioned in that thread, any `AARs` and `JARs` will need to be in either local or remote maven repos so they're processed by the Android Resolver.  If you are using custom gradle template mode, a.k.a. mainTemplate.gradle, the Jetifier integration in the Android Gradle build will process them.

**Comment by chkuang-g** [comment]
Hi @thomasjohnwolfe 

So since you are using gradle template mode, a.k.a mainTemplate.gradle, let's use this as the baseline.

1. For plugins which is using EDM to resolve dependency, such as `Admob`, `Firebase`, `Google Play Games`, and `Facebook`, it is not necessary to upgrade them since
   - AndroidResolver from EDM will inject dependencies and local repo to mainTemplate.gradle for you already.  See `// Android Resolver` sections.  If you did not see those sections, you probably did not enable it in the settings.  Take a look at `Assets > External Dependency Manager > Android Resolver > Setting` menu item.
   - If you enable Jetifier in Android Resolver, mainTemplate.gradle should enable "android.enableJetifier`.  That means, when you build for Android, Gradle will use Jetifier to patch all `.aar` and `.jar` from the local or remote repo for you.
1. For plugins which come with `.aar` and `.jar`, this is basically a nightmare for you developers.  The worst case is that they include legacy Android support library as well.  In this case, you need to prune the weed for them.
   - First of all, find all `.aar` and `jar` that are just a dependency.  Ex, files start with `androidx.` or `android.` are definitely are dependencies.  Remove them.
   - Second, find all the rest of `.aar` and `.jar`, create one or more POM file for them to make local repos.  Add the repo path to mainTemplate.gradle manually.  In this case, as mentioned, Gradle should patch those libraries for AndroidX as well.
   - Write a nice letter to the plugin developer and ask them to use EDM.
1. For the `.aar` and `.jar` your team made, create one ore more POM file to make local repos, and add the path to mainTemplate.gradle as well.

I think this should cover most of the use case.  Unfortunately Unity does not provide an official methods to remove Android dependencies.  We can only hope more plugin provide can follow EDM standards so that the developer can spend less effort managing them.

Let us know if it helps!

**Comment by thomasjohnwolfe** [comment]
Thank you very much for your response. Will keep you updated with results.

**Comment by thomasjohnwolfe** [comment]
> 3. For the .aar and .jar your team made, create one ore more POM file to make local repos, and add the path to mainTemplate.gradle as well as dependencies.

Where does this POM file live? Currently our process is to export a .jar file and then put int in `UnityProject/Assets/Android/Plugins`. Is this similar to the root `build.gradle` file in the Android project?

```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

allprojects {
    repositories {
        maven { url "http://appboy.github.io/appboy-android-sdk/sdk" }
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```


TBH our studio is Unity3d based and not native Android developers by trade (only when we have to be) so I actually was just researching [what a POM file is](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) for the first time right now. If you have any documentation you could point me to, would be appreciated. Thanks.

**Comment by patm1987** [comment]
If you want to see a good example of a local maven repo with POM files, check out `Assets/Firebase/m2repository` that ships with the Firebase SDK. This is a local Maven repository for just the C++ portions of the Firebase SDK.

The POM file should automate your manual downloading. You could also point your Dependencies.xml file to the maven repo to pull down things that way, I did a brief writeup of the External Dependency Manager for Unity [here](https://medium.com/firebase-developers/how-to-manage-your-native-ios-and-android-dependencies-in-unity-like-firebase-921659843aef?source=friends_link&sk=8db8be3ebd2b2e2452fb9ef440a9cf7a) (when it was called the Play Services Resolver, but it should still hold).

--Patrick

**Comment by thomasjohnwolfe** [comment]
Still an issue. Just getting time to work on it is difficult. Will keep you posted.

**Comment by patm1987** [comment]
No worries!
