### ISSUE TITLE
Fake 'Resolution Successed' message! without Resolving!

### ISSUE THREAD

**Issue by smkplus** [googlesamples/unity-jar-resolver#371]
### Please fill in the following fields:
Unity editor version:  Unity 2018.4.5f1
External Dependency Manager version: latest version
Source you installed EDM (from .unitypackage or Unity Package Manager):
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.):
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Tapsell
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:
'Resolution Successed' but I can't export!!!

![image](https://user-images.githubusercontent.com/16706911/81385220-3610a000-9128-11ea-97c2-d1be20e06ec8.png)

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)

I don't know why sometimes resolution not work 
when I force resolve, it immediately writes `Resolution Successed` without opening resolving window!

![image](https://user-images.githubusercontent.com/16706911/81384449-ec738580-9126-11ea-831f-50c9f60ec5f8.png)

I have to export my game by android studio but didn't work
```
AndroidJavaException: java.lang.ClassNotFoundException: ir.tapsell.sdk.TapsellUnity
    java.lang.ClassNotFoundException: ir.tapsell.sdk.TapsellUnity
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
        at android.os.MessageQueue.next(MessageQueue.java:395)
        at android.os.Looper.loop(Looper.java:181)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "ir.tapsell.sdk.TapsellUnity" on path: DexPathList[[zip file "/data/app/com.hppni.hokmas-bGtGmf4BOJX9Xzkf1KJiYg==/base.apk", zip file "/data/app/com.hppni.hokmas-bGtGmf4BOJX9Xzkf1KJiYg==/split_lib_de
```

**Comment by Khaled-Wolf** [comment]
I am having the same issue,
Please try to uncheck use Custom Gradle Template
I unchecked the Custom Gradle Template option and did a successful resolve
then If I re-enabled Custom Gradle Template again the resolve result will be removed from the project, I am not sure if that is on purpose

**Comment by smkplus** [comment]
@Khaled-Wolf thanks it worked on another computer but I don't know why it didn't work on my computer :(

**Comment by chkuang-g** [comment]
@smkplus 

I am not familiar with Tapsell.  Does this plugin includes its own Dependencies.xml?  Is it possible that they configure their plugin incorrectly so that `Custom Gradle Template` mode simply does not work?
Also, which version of External Dependency Manager (formally called Play Services Resolver) does it use?

Here is some explanation.

- When `Custom Gradle Template` is unchecked, Android Resolver will try to download all the dependencies from maven repos, based on Dependencies.xml, to `Assets/Plugins/Android/` folders so that Unity can use them to make Android build.
- When `Custom Gradle Template` is checked, all the libraries are downloaded and resolved during the build time using gradle.  Therefore, all of the resolved libraries under `Assets/Plugins/Android/` folder will be removed.  What Android Resolver does is to inject the repo path and dependencies from Dependencies.xml to mainTemplate.gradle, so that gradle can use it to resolve/download dependecies.

Perhaps you should consult with the maker of Tapsell to resolve this issue.
Shawn

**Comment by Khaled-Wolf** [comment]
>     * When `Custom Gradle Template` is checked, all the libraries are downloaded and resolved during the build time using gradle.  Therefore, all of the resolved libraries under `Assets/Plugins/Android/` folder will be removed.  What Android Resolver does is to inject the repo path and dependencies from Dependencies.xml to mainTemplate.gradle, so that gradle can use it to resolve/download dependecies.

@chkuang-g 
Tried this approach with the following:
New Project
Unity 2017.4.39 (LTS)
Firebase for Unity 6.14
ExternalDependencyManager v1.2.152
Custom Gradle Template is checked
Build Settings -> Export Project is checked
After exporting the project and opening in Android Studio (3.6.3)
I get this error message 
ERROR: Failed to resolve: firebase-analytics-unity
Affected Modules: Firebase

if Custom Gradle Template is Unchecked 
the project will be exported correctly
