### ISSUE TITLE
gradle failed to fetch dependencies - Could not create an instance of type org.gradle.initialization.DefaultSettings_Decorated.

### ISSUE THREAD

**Issue by Estellise-Esuteriize** [googlesamples/unity-jar-resolver#379]
This is my first issue, so I don't know if this is correct or wrong.

### Please fill in the following fields:
Unity editor version:  2019.3.5f1
External Dependency Manager version:  1.2.155
Source you installed EDM (from .unitypackage or Unity Package Manager): Unity Package Manager
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.):  Android Resolver, IOS Resolver, and VersionHandler
Plugins SDK in use (Firebase, Admob, Facebook, etc.):  Firebase Database, Firebase Firestore, Firebase Analytics, Firebase Authentication, and Firebase Core
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac
Platform you are targeting (iOS, Android, and/or desktop): IOS and Android
Scripting Runtime (Mono, and/or IL2CPP):  IL2CPP

### Please describe the issue here:
[gradle failed to fetch dependencies](https://github.com/googlesamples/unity-jar-resolver/files/4744211/gradle_fetch_dependencies.txt)

**Comment by chkuang-g** [comment]
@Estellise-Esuteriize 

This seems to be an issue from Groovy side. 
https://github.com/gradle/gradle/issues/10248

Are you using OpenJDK coming with Unity 2019?

**Comment by Estellise-Esuteriize** [comment]
Hi, @chkuang-g I am using the OpenJDK that comes with unity 2019 but I still get the error, but when I uncheck-check it like 2x or when I just uncheck it and point it the Unity OpenJDK path it'll works.

This is the java version currently in my mac.
![image](https://user-images.githubusercontent.com/44573967/84499558-70e89380-ace5-11ea-8bcd-6552d27da285.png)

**Comment by chkuang-g** [comment]
This seems specifically occurs to OpenJDK 14. 

What if you install Java 8 and point you Unity to `/Library/Java/JavaVirtualMachines/your-version-of-java-8`

https://www.java.com/en/download/help/mac_10_10.xml

**Comment by chkuang-g** [comment]
As suggested in https://github.com/googlesamples/unity-jar-resolver/issues/384, bumping up gradle version seem to resolve this issue.

I'll bump up the gradle version to 6.5 in the next release.

**Comment by chkuang-g** [comment]
@Estellise-Esuteriize

Upgrading to 6.5 turns out to be quite a task since Gradle 6 introduced many breaking changes.  The most concerning one is the version range.
https://docs.gradle.org/current/userguide/single_versions.html

In Gradle 5, version range `1.0.0` actually means `any version greater than 1.0.0, up to but not including 2.0.0`. 
The new version scheme may cause Android Resolver to fail to resolve dependencies.

AFAIK, Unity 2020 is using Gradle 5.6.  Therefore, I would not recommend to bump up Gradle version to 6 unless you are sure all Android libraries are resolved properly.

Since this is an issue in OpenJDK, the best resolution is still using later version of OpenJDK or just install Java 8.

Hope this helps!

Shawn
