### ISSUE TITLE
Different line endings when generating GvhProjectSettings from a different OS

### ISSUE THREAD

**Issue by ricardobustaw** [googlesamples/unity-jar-resolver#386]
### Please fill in the following fields:
Unity editor version: 2018.4.23f1
External Dependency Manager version: 1.2.156
Source you installed EDM (from .unitypackage or Unity Package Manager): .unitypackage
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver, iOS Resolver, VersionHandler
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase, Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac and Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
File was generated and committed to project repo from a mac machine, but when a windows developer opens the project, gvh file is generated with different line ending, causing it to show changes on git.

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

Repro steps: 
- Save the file in a mac machine
- Commit to repo.
- Open from windows machine
- See difference in line endings

![image](https://user-images.githubusercontent.com/62283059/86612534-8f723f80-bfb0-11ea-8a8b-c9d09a1298fd.png)

**Comment by alexames** [comment]
Hi @ricardobustaw 

Thanks for the report. Taking a quick glance at the code, it looks like we just need to make the XML writer here:
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/VersionHandlerImpl/src/ProjectSettings.cs#L820

...behave more like one set up here:
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/LocalMavenRepository.cs#L166

If you'd like to make the change yourself, feel free to do so and submit a pull request. Otherwise, we'll make the change in a bit as time allows.

**Comment by ricardobustaw** [comment]
Thanks for the idea! If we manage to do something before you have a solution for that, we will surely create a PR! :)
