### ISSUE TITLE
Why is there `PlayServicesResolver` folder in EDM?

### ISSUE THREAD

**Issue by CodeMasterYi** [googlesamples/unity-jar-resolver#388]
![B8A2CB14-3C41-4C43-89DE-274052A524C8](https://user-images.githubusercontent.com/10430162/87011706-dbb0c000-c1fa-11ea-9bb0-4e2b148e1e76.png)

**Comment by chkuang-g** [comment]
This is a workaround to make sure the renaming from `play-services-resolver` -> `external-dependency-manager` work properly since 1.2.138, if there is any older version of Play Services Resolver in the project.  This should be automatically removed or at least prompt to be deleted after newer version of EDM4U is installed.

Shawn

**Comment by CodeMasterYi** [comment]
Nay!
