### ISSUE TITLE
Plugin Redistribution if adding dependency via Unity Package Manager

### ISSUE THREAD

**Issue by vegaro** [googlesamples/unity-jar-resolver#393]
Sorry if this is more of a question but I am not sure if the README instructions for how to distribute the plugin have been updated. We use this plugin in https://github.com/RevenueCat/purchases-unity and we distribute our plugin as a .unitypackage

We have a project called "Subtester" that we use to export the plugin. The way we used to export the plugin was:

1. Delete Assets/PlayServicesResolver in the Subtester project, close Unity. (I am not sure this step was needed)
2. Open Unity with the `-gvh_disable` flag: `/Applications/Unity/Hub/Editor/2019.3.0f3/Unity.app/Contents/MacOS/Unity -gvh_disable -projectPath Subtester`
3. Add the latest version of `PlayServicesResolver` (maybe if we don't delete in step number 1, we don't have to do it? If I understand correctly we have to run with `gvh_disable` and then reimport before exporting)
4. Export the package including the `Assets/PlayServicesResolver` but don't include the `Plugins/Android` with all the aars downloaded by `PlayServicesResolver`

I think that approach worked fine.

The problem we are seeing now is that when we import the plugin and it gets added under the Packages folder, since it's now managed via Unity Package Manager:

![Screen Shot 2020-07-29 at 2 15 12 PM](https://user-images.githubusercontent.com/664544/88854297-ecbf7200-d1a5-11ea-9679-2e939955e67f.png)

So when we try to export the package, we can't export the folder inside Packages.

According to your documentation for Plugin Redistribution:

> Import the external-dependency-manager-*.unitypackage into your plugin project by running Unity from the command line, ensuring that you add the -gvh_disable option.

Does this mean that we have to remove the External Dependency Manager plugin from the Packages before running Unity with `-gvh_disable` and importing again?

> Export your plugin by running Unity from the command line, ensuring that you:
Include the contents of the Assets/PlayServicesResolver directory.
Add the -gvh_disable option.

The `Assets/PlayServicesResolver` contains a `txt` with a version 1.2.137 whereas the latest version of the plugin is 1.2.156. The content of the txt is two paths that don't even exist in the plugin:

```
Assets/PlayServicesResolver/Editor/Google.VersionHandler.dll
Assets/PlayServicesResolver/Editor/Google.VersionHandler.dll.mdb
``` 

I think this Assets/PlayServicesResolver might be leftovers from previous versions and this step should be:
```
Export your plugin by running Unity from the command line, ensuring that you:
Include the contents of the `Assets/ExternalDependencyManager` directory.
Add the -gvh_disable option.
```

Is that correct? If the plugin is added via Unity Package Manager, `Assets/ExternalDependencyManager` will be empty.

I am sorry if these are basic questions, but we are struggling to understand how we are supposed to export our plugin correctly. To summarize, we have two questions:

1. How do we export our unitypackage and make sure people that install it also get the ExternalDependencyManager?
2. Do we have to uninstall ExternalDependencyManager before running unity with `-gvh_disable` before exporting?

**Comment by chkuang-g** [comment]
@vegaro 


1. I think the instruction [here](https://github.com/googlesamples/unity-jar-resolver#plugin-redistribution) should still be valid.
`-gvh_disable` just disables Versoin Handler while exporting so that it will not modifying any meta files during the export.
That text file under `Assets/PlayServicesResolver` folder is a workaround to make sure that Version Handler can properly remove the older version of libraries before renaming from `Play Services Resolver` to `External Dependency Manager`.  It is general good idea to include this in your project as well, since the user can get EDM4U from many different sources in different versions, including Firebase, ARCore, GoogleAds, and several 3rd party SDKs like Facebook.

2. 
When you are exporting your plugin with EDM4U(External Dependency Manager for Unity), you will need to remove the one under `Packages` folder, through Unity Package Manager, and install it to `Assets` folder. Otherwise, as you find out, `Assets/ExternalDependencyManager/Editor` will be empty because files with same GUID are installed under `Packages`.
As a plugin distributor, you probably want to avoid installing EDM4U from Unity Package Manager.

Hope this answer your question!
Shawn

**Comment by vegaro** [comment]
Thanks so much for your answer @chkuang-g, that basically confirms what I was thinking!

The step in the instructions:

`Include the contents of the Assets/PlayServicesResolver directory.`

Should be updated to:

`Include the contents of the Assets/PlayServicesResolver and Assets/ExternalDependencyManager directories.`

Right? Happy to make a PR if you confirm 😃

**Comment by chkuang-g** [comment]
Thanks for the suggestion.

I'm going to make a release pretty soon so I will include this change in the new release.

**Comment by vegaro** [comment]
@chkuang-g I have another related question, if we start distributing our plugin via the UPM, how would we include EDM4U as a dependency? Should we tell our users to add it manually? Or do we have to keep distributing it along with our plugin?

**Comment by chkuang-g** [comment]
@vegaro 

Short answer: you need to add EDM4U as a dependency in your `package.json`(https://docs.unity3d.com/Manual/CustomPackages.html) and make sure the user's project added both yours and Google's registry server in their project.

Of course, first you need to have your own registry, and have your package uploaded to there.  There are some online tutorial about how to make your own npm server for UPM.  But please evaluate the security and scalability for those solution carefully.

Second, you need to add EDM4U as dependency. As mentioned, you just need to add something like 
```
    "com.google.external-dependency-manager" : "1.2.156"
```
to your package.json

Third, you need to ask the user to add your registry as [scopedRegistry](https://docs.unity3d.com/Manual/upm-scoped.html).  EDM4U actually shipped a [solution](https://github.com/googlesamples/unity-jar-resolver#package-manager-resolver-usage) which will prompt to add registries specified in `Registries.xml`. 

Finally, EDM4U offers a solution to migrate packages installed to `Assets` folder to `Packages` folder.  However, this requires you to add a manifest file and label the assets in your package properly so that [Version Handler](https://github.com/googlesamples/unity-jar-resolver#version-handler-usage) can recognize them properly.  It also requires a special `keywords` in your package.json.
```
   "vh-name:your-package-name"
```
This part is used by Firebase but not well documented.  Let me know if you need to do this.

Shawn

**Comment by chkuang-g** [comment]
Hi @vegaro 

I updated the README.md, thanks for the suggestion.

I'll close this issue for now
