### ISSUE TITLE
Some conflicting dependencies were found. Crashing APK after successful build.

### ISSUE THREAD

**Issue by nikpik7** [googlesamples/unity-jar-resolver#397]
Unity editor version: 2019.1.1f1
Added Play Services API from GitHub 0.9.64
Scripting Runtime  IL2CPP
Updated game to x64 support with SDK n NDK

### Please describe the issue here:
Builds Fine but App crashes when run on Phone

Issue after force resolver

![unity issue](https://user-images.githubusercontent.com/69907459/90643008-b333d100-e250-11ea-9be6-d467e5b0c48e.PNG)
Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
com.google.games:gpgs-plugin-support:0.9.64 --> com.google.games:gpgs-plugin-support:+

**Comment by cynthiajoan** [comment]
Hi @nikpik7, this error usually means you have two different sdks that depend on two different versions of these two packages. Usually upgrade them to the latest version should fix the issue.

If you can provide the information from Assets->EDM->Android Resolver->Display Libraries to help us understand the project setup better, that would be great.

**Comment by chkuang-g** [comment]
@nikpik7 

Judged by your callstack, try this menu item to see all Android dependencies in your project.
```
   Assets > Play Services Resolver > Android Resolver > Display Libraries
```

There are definitely conflict dependencies in your project. When you see log like this
```
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
com.google.games:gpgs-plugin-support:0.9.64 --> com.google.games:gpgs-plugin-support:+
```

This means that there are two or more different plugins depends on very different version of `com.google.android.gms:play-services-ads` and `com.google.games:gpgs-plugin-support`.  Play Services Resolver (or External Dependency Manager now) can only warn you when this happens since picking either one version of them are fairly dangerous

Try to find all files end with `Dependencies.xml`.  And potentially upgrade those plugins to later version to resolve this issue.

**Comment by nikpik7** [comment]
Only Solution i got till now is to uninstall and install clean  as there are high chances  the  conflict is happening because of the some files clashing. 
Thank you for Support.
