### ISSUE TITLE
What are the exact JDK Installation requirements for EDM4U to process android libraries on Windows and Mac?

### ISSUE THREAD

**Issue by ferretnt** [googlesamples/unity-jar-resolver#404]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.11
  * External Dependency Manager version: 1.2.160
  * Source you installed EDM4U: Unity Package Manager
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase RTDB + Dependencies, Facebook (but can repro without facebook)
  * Platform you are using the Unity editor on: Mac OSX 10.15.7 (Catalina) (can also repro on Windows.) 

### [REQUIRED] Please describe the question here:

It remains unclear what the requirements for Java are for EDM4U to function correctly. Unity installs OpenJDK, yet we cannot get EDM4U to resolve on a clean install (i.e. fresh machine) with just Unity, unless: 

(a) We explicitly install a JDK (additional system thing to manage, unnecessary) 
OR 
(b) We *uncheck* "Use builtin [SDK/NDK/Java/etc]" in Unity preferences, and paste their values to point to exactly the same place. This causes issues when upgrading between versions of Unity. 
(c) We explicitly set a JAVA_HOME environment variable. 

The testing matrix for android dependencies is a nightmare and causes hours of wasted time setting up our build machines. Can we please have some clarification on the minimum required setup for EDM4U to function correctly (seems Android is the issue) on both Windows and Mac machines - specifically.

- whether any JDK install is necessary
- whether any environment variables (JAVA_HOME) should be set
- whether it is expected that EDM4U works with "Use builtin NDK/SDK/Gradle/JDK" (i.e. the default that Unity installs with) checked. 

The Unity JAR Resolver main page is conspicuous in its absence of any mention of Java. 

Googling or searching youtube for information on the minimal and correct way to setup results in lots of hearsay and works-on-my-machine with no concrete knowledge. 

Here is an example from opening a project containing EDM4U on the Mac (os version listed above.) Note that running sdkmanager command below from terminal DOES work, but that's because I have explicitly put in ~/.zshrc the following line: 

export JAVA_HOME=/Applications/Unity/Hub/Editor/2019.4.11f1/PlaybackEngines/AndroidPlayer/OpenJDK/

If EDM4U requires explicit setting of environment variables, we would like that to be documented, so that people don't have to be confused about why EDM4U doesn't work in their setup, and what the minimal and officially supported setup to fix it is. 

To date we have only been able to consistently run EDM4U Android Resolver by explicitly installing JDK 8u152 from Oracle. 

-- Unity project output follows

Unable to determine which Android packages are installed.
Failed to run '/Applications/Unity/Hub/Editor/2019.4.11f1/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --list --verbose'
stdout:

stderr:
No Java runtime present, requesting install.

exit code: 1

UnityEngine.Debug:Log(Object)
Google.Logger:Log(String, LogLevel) (at Z:/tmp/tmp.USknC9AJqk/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:124)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at Z:/tmp/tmp.wTtEZeV6oc/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1053)
GooglePlayServices.<QueryPackages>c__AnonStorey0:<>m__0(Result) (at Z:/tmp/tmp.wTtEZeV6oc/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/AndroidSdkManager.cs:433)
GooglePlayServices.ProgressReporter:SignalComplete() (at Z:/tmp/tmp.wTtEZeV6oc/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at Z:/tmp/tmp.wTtEZeV6oc/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey1:<>m__0() (at Z:/tmp/tmp.wTtEZeV6oc/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/CommandLine.cs:137)
Google.RunOnMainThread:ExecuteNext() (at Z:/tmp/tmp.USknC9AJqk/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1() (at Z:/tmp/tmp.USknC9AJqk/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.USknC9AJqk/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at Z:/tmp/tmp.USknC9AJqk/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.USknC9AJqk/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)

**Comment by steve6t6** [comment]
Hello

We too cannot get EDM4U to resolve dependancies for Firebase SDK (Database, Auth, Analytics, Storage, Functions) using only the shipped OpenJDK.

Using Unity 2019.3.4f1 and Firebase 6.16.0

**Comment by ferretnt** [comment]
> Issue 806

To be clear, do you mean "we can now build *with* an external JDK installed" or "we can now build with a vanilla machine and only the unity-installed OpenJDK?" 

I'm trying to event this thread becoming one more "we changed some stuff that may or may not be related and it's OK now" thread. To be clear, *I* can build successfully, but that's because I've explicitly installed the JDK on any build machines. Unity Cloud Build can also build iOS+Android with Fireabase and Facebook SDKs, probably because it has a JDK installed.

**Comment by steve6t6** [comment]
@ferretnt My apologies for using vague language. We are making builds on our local machine, a MacBook air running Catalina, we do not use cloud build at this time. We use OpenJDK installed by Unity Hub and Unity 2019.3.4f1 exclusively. Upon another clean install of the Firebase 6.16.0 SDK using the UPM we found Force Resolve always failed, claiming there was no Java runtime, and Android builds reported errors caused by conflicting Firebase plugin Android Manifests. Issue 806 helped us resolve the conflicts, then Force Resolve just suddenly worked.

**Comment by chkuang-g** [comment]
Hi folks,

I am seeing the same error while using Unity 2019 as well.
```
Unable to determine which Android packages are installed.
Failed to run '/Applications/Unity/Hub/Editor/2019.4.11f1/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --list --verbose'
```

And it usually can be resolved by **TOGGLING** `Use builtin [SDK/NDK/Java/etc]`, which is very very odd.
Since both Java 8 and OpenJDK installed through Unity works after the toggling, I truly believe there are some issues in Unity about this.

EDM4U itself actually does not require Java or OpenJDK at all.  It does requires Gradle 5 to resolve dependency when Custom Gradle Template is not checked. And [Gradle requires Java 8 or above](https://gradle.org/install/).  All of the code in EDM4U are written in C# as you can see in this repo.

However, I saw this error at build time because Unity is trying to use Gradle to build an Android binary.  That portion is developer by Unity. 

There are several action you can take:
1. Try to run `/Applications/Unity/Hub/Editor/2019.4.11f1/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --list --verbose` in iTerm and see if there is any error.  If not, it is most likely an Unity issue.
2. I _think_ I stop to see those errors in the later version of Unity.  Another you can try is to upgrade your Unity version.

This is truly frustrating but unfortunately I have no clue about what is causing it.

Shawn
