### ISSUE TITLE
how to set credentials in androidPackage

### ISSUE THREAD

**Issue by lukeZlp** [googlesamples/unity-jar-resolver#406]
with my unity project, i`ll use a android sdk from maven need set credentials.
ex ：
 maven {
            url 'http://xxx/repository/maven-public/'
            credentials {
                username = 'username '
                password = 'password '
            }
        }
thanks for answer~

**Comment by chkuang-g** [comment]
Hi @lukeZlp 

Do you mean that you need to setup the `Dependencies.xml` in your plugin so that it can configure the Gradle file with Maven repo using a specific credential? If that is the case, I do not thing EDM4U supports that yet, since it does not make sense to publish your plugin with credential in it.

Or do you mean how do editor `mainTemplate.gradle` so that it can include a Maven repo using credential?
In that case, you can follow this manual and edit `mainTemplate.gradle` directly. No EDM4U needed.
https://docs.gradle.org/5.1.1/userguide/repository_types.html#sub:authentication_schemes

Hope this helps,
Shawn
