### ISSUE TITLE
[Bug] Failed to determine the most recently installed Android SDK version with Unity 2019.4.20f1 LTS

### ISSUE THREAD

**Issue by haroongamepace** [googlesamples/unity-jar-resolver#424]
Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogError(Object)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:298)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:120)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2236)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1617)
GooglePlayServices.<ScheduleResolve>c__AnonStorey1E:<>m__40() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1586)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1445)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1599)
GooglePlayServices.PlayServicesResolver:ExecuteMenuResolve(Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1806)
GooglePlayServices.PlayServicesResolver:MenuForceResolve() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1829)

**Comment by raslab** [comment]
Same issue on Unity 2019.4.14f1 (LTS) for mac.

**Comment by chkuang-g** [comment]
Hi @haroongamepace @raslab Could you give us a bit more context about how you reach to this error message?  Like fill up the template as the following.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * External Dependency Manager version: _____
  * Source you installed EDM4U: _____ (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: _____ (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: _____ (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.
