### ISSUE TITLE
securuty

### ISSUE THREAD

**Issue by viviskas** [googlesamples/unity-jar-resolver#445]
_my pc.... i dondt speak english.... you a helpfull debug end reset alldata my   
all my data pc reset or create help delete virus, reg options reset windows 10 x64, virus kill my outlock, dont me rules  # drive os,..i dont cnow how to delete virus, (0.5 year attack me)_

**Comment by viviskas** [comment]
notifications me, 21:00 MSC(MOSCOW TIME),
AND I CONNECT USB IN MOTHERBOARD PC, YOU HELP ME??????

**Comment by viviskas** [comment]
"Make sure you provide all the required information." ????? what help my microsoft win10?

**Comment by paulinon** [comment]
Hi @viviskas,

It seems that you're facing an issue with your Windows implementation. You may get in contact with their [support channel](https://support.microsoft.com/) so that someone knowledgeable about this issue can help you out. With that, I'll be closing this for now.

If you have any issues with the resolver in your Unity project, please let me know.
