### ISSUE TITLE
Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-gcm

### ISSUE THREAD

**Issue by AbdullahAlimam** [googlesamples/unity-jar-resolver#45]
Hi I got this error in my Unity 3D project

Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-gcm:9+
  at Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at OneSignalEditorScriptAndroid.addGMSLibrary () [0x00033] in D:\Tatweer\Foodak\Mobile\Unity Project\Assets\OneSignal\Editor\OneSignalEditorScript.cs:51 
  at OneSignalEditorScriptAndroid..cctor () [0x0001a] in D:\Tatweer\Foodak\Mobile\Unity Project\Assets\OneSignal\Editor\OneSignalEditorScript.cs:43 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()

I update the Libraries from Andriod SDK Manager but I still got this problem

**Comment by AbdullahAlimam** [comment]
I remove it from the project then install the new Version.

Now I got this error:

NullReferenceException: Object reference not set to an instance of an object
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest, System.String destDirectory)
GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation)
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey5.<>m__8 ()
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.AutoResolve ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:197)

**Comment by stewartmiles** [comment]
@AbdullahAlimam  the Jar Resolver looks for dependencies in the:
- ${ANDROID_SDK}/extras/google/m2repository/
- ${ANDROID_SDK}/extras/android/m2repository/

directories on your machine where ${ANDROID_SDK} is the install path of the Android SDK which is typically determined by your Android configuration in Unity.  e.g on one of my dev machines, I have...

~/android-sdk-macosx/extras/google/m2repository/com/google/android/gms/play-services-gcm/10.2.0/play-services-gcm-10.2.0.aar

So I recommend checking that you have configured your Android SDK directory correctly in Unity.  In addition, you could turn on verbose logging under "Assets > Play Services Resolver > Android Resolver > Settings" to see what's going on (e.g where it's searching etc.).

In terms your most recent post, it looks like you're tickling a bug.  Any chance you could build the project (https://github.com/googlesamples/unity-jar-resolver/blob/master/source/JarResolver.sln) and copy JarResolver.dll and JarResolver.dll.mdb into your project in order to get a complete annotated stack trace?

**Comment by AbdullahAlimam** [comment]
@stewartmiles I check my directory of Andriod SDK and there is just 
${ANDROID_SDK}/extras/android/m2repository/

How Can I get the google path?

**Comment by AbdullahAlimam** [comment]
Sorry I solve it, 
there were 2 Andriod SDK Locations in my PC
I select the New One with the latest updates from Edit performances in unity then restart the project.

Now everything is fine

thanks
