### ISSUE TITLE
Failed to determine the most recently installed Android SDK version.

### ISSUE THREAD

**Issue by Breaktherecords** [googlesamples/unity-jar-resolver#458]
Failed to determine the most recently installed Android SDK version.
Every time when i am going to build apk and web build

**Comment by paulinon** [comment]
Hi @Breaktherecords,

This is likely related to your Unity configuration. Later versions of the editor usually require a minimum API version of 19. It's recommended that you use OpenJDK and Android SDK installed through Unity Hub. Otherwise, if you like to use your own, please make sure the required version is installed and set correctly in your Preferences > External Tools.

I'll be closing this for now. Let me know if the issue persists or if this solution doesn't suit your use case.
