### ISSUE TITLE
Keep library

### ISSUE THREAD

**Issue by syslord2k2** [googlesamples/unity-jar-resolver#46]
The jar-resolver keeps deleting the belvedere library (https://github.com/zendesk/belvedere) that i copied into the Plugins/Android folder. The first time it builds it only explodes it and deletes it on the second build. Is there a ways to specifically forbid the jar-resolver to do this?
The jar-resolver is called only by the AppDeps and the MessagingDeps of the Untiy Firebase plugin.

**Comment by stewartmiles** [comment]
Looks like the problem is here:
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/ResolverVer1_1.cs#L869

We're blindly slurping up all AARs and processing them which is problematic
for your use case.

Since we now label AARs / JARs we copy into Plugins/Android we should
probably only manage files that are labeled and ignore the rest.

For the moment you should be able to disable auto resolution, not great I
know.

Cheers,
Stewart

**Comment by stewartmiles** [comment]
This is "fixed" in 37e7e2f2fb975f70994a6837016d5ff95b037490 .  I decided to entirely disable processing AARs that aren't specified as Jar Resolver dependencies as it gets pretty messy.  If you want to have the Jar Resolver explode the AAR you can copy the maven repo into your project (create a local maven repo) then add a dependency on the package with a reference to the repo and the Jar Resolver will process the AAR as per usual.  If you want an example, check out the Firebase Unity plugins, they ship with a m2repository directory that constitutes a local Maven repo for a subset of the components.
