### ISSUE TITLE
Can't finish step 1

### ISSUE THREAD

**Issue by pgilmorepf** [googlesamples/unity-jar-resolver#53]
Following the instructions here:
https://github.com/googlesamples/unity-jar-resolver#usage

I downloaded the unitypackage:
https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.21.0.unitypackage
And added it to my unity project

I put a copy of this file in my project:
https://github.com/googlesamples/unity-jar-resolver/blob/master/sample/Assets/PlayServicesResolver/Editor/SampleDependencies.cs

This is where I'm stuck.
Assets/PlayServicesResolver/Editor/SampleDependencies.cs(69,36): error CS0103: The name `Google' does not exist in the current context

This issue:
https://github.com/googlesamples/unity-jar-resolver/issues/26
Remains unanswered for previous people with this question.

**Comment by Amikarimi** [comment]
Http://github.com/googlesamples/unity-jar-resolver/blob/master/sample/Assets/playserviceResolver/Editor/SampleDependencies.cs(#26)

**Comment by stewartmiles** [comment]
@pgilmorepf if you're seeing a missing "Google" namespace that's due to the plugin being enabled by the VersionHandler component.  Try:

- Select the "Assets > Play Services Resolver > VersionHandler > Settings" menu item
- Check "Enable version management"
- Check "Verbose logging"
- Press "OK"
- Select the "Assets > Play Services Resolver > VersionHandler > Update" menu item to enable the Play Services Resolver.

By default this should happen on import, if this isn't happening on a clean install could it be that your project has compile errors which is preventing the DLL to execute?

**Comment by stewartmiles** [comment]
We've simplified dependency management in 1.2.47 c532ffe88dd6ffa628ef5da43acbdadafcb8e1a8
