### ISSUE TITLE
[FR] Resolver full log copy/export

### ISSUE THREAD

**Issue by gerchicovy** [googlesamples/unity-jar-resolver#534]
### Feature proposal

* EDM4U Component: Android Resolver

In my case I see a strange source dependency and I need to search for it in resolver logs but I can't do it because resolver doesn't support text search and doesn't allow to copy this log to another editor

**Comment by chkuang-g** [comment]
Hi @gerchicovy 

Do you mean you want to be able to copy the text from this Android Resolver UI?

<img width="606" alt="Screen Shot 2022-08-22 at 1 52 22 PM" src="https://user-images.githubusercontent.com/31869252/186016831-1743531f-a5aa-4ea8-876e-3305889a6b11.png">

If so, you should be able to select text in this UI box and Ctrl+C to copy them.

Alternatively, you can also turn on the `verbose log` in Android Resolver setting.  Then all the log should go to Unity editor log.

Is this what you need?  Or are you using `mainTemplate.gradle` and want to get the resolution log from Unity?

Also, which Unity version and EDM4U version are you using?

Shawn

**Comment by userCTest** [comment]
Hey Guys, 
I think what @gerchicovy is looking for, and so am I, is the possibility of having the resolving dependencies output sent to a text file, so that one can search through it. Some output can be quite amazingly long and it simply becomes impossible to copy and paste in its entirety.

Thx in advance!
Rui
