### ISSUE TITLE
iOS Resolve Dependencies Menu Option

### ISSUE THREAD

**Issue by dwxw** [googlesamples/unity-jar-resolver#59]
Hello,  is there a plan to add a method and or menu option to explicitly resolve the cocoapod dependencies as you currently can with Android (GooglePlayServices.PlayServicesResolver.MenuResolve())?  I ask because I'm trying to build a plugin that allows dependencies to be switched in and out from the editor, but I can't find a way of removing pods without restarting the editor.
Thanks.

**Comment by stewartmiles** [comment]
Pods are injected as a build step rather than in the editor.  If we add
functionality to add frameworks to a project similar to the Jar Resolver
then we'll add a menu option.  If you want to disable pods in your build
you'll need to disable the IOS resolver from the settings menu.

Cheers,
Stewart

**Comment by dwxw** [comment]
I understand you're injecting the Pods as a build step but UnityJarResolver can only finds the pods to be added when the editor loads.  I would like to be able to add / remove the pods that will be added to the build step via my own editor plugin.  I have code for doing this just now, including generating the Podfile and running pod install in a post process step, but we've already started to move our Android dependencies to UnityJarResolver so I'd like to do the same for iOS.  At the moment, I can change my Dependencies.cs file from an editor plugin and call RegisterDependencies again, but that can only add to the list of pods that will be added because pods is static and the only public method is AddPod.  With Android you can call MenuResolve and search for all the dependencies from scratch.  I was asking if you have a plan to add an equivalent function for iOS, as that neatly solves my problem.

Otherwise this project is fantastic and really made life easier on the Android side of things.  Thanks again.  David.

**Comment by stewartmiles** [comment]
The way I've been thinking about taking this is moving away from an API
entirely to add / remove dependencies.  Instead we would simply have config
files specify the set of Android / iOS dependencies (e.g xml / json files)
these would be parsed during the resolution step which for Android is on
plugin load or when a relevant asset changes and for iOS this is during the
post build step.

You mention you're adding / removing dependencies I assume this is because
features are being enabled / disabled?  If so would dropping / modifying
dependency config file(s) in your plugin be feasible?

With the current state what you could do to force a reload - assuming you
specify dependencies in .cs files - is reimport the IOSResolver dll using
the PluginImporter class, that will force it to reload and refresh all
dependencies.

Cheers,
Stewart

**Comment by dwxw** [comment]
A config file that's read when required is pretty much how I'm doing it at the moment.  I actually have a template Podfile I add and remove dependencies too.  It's nowhere near as robust as your code and won't work if someone else is wanting to add their own dependencies.

I'm actually adding and removing ad libraries.  I have a little editor window to allow the developer to select which ad networks to add into their game.  The Cocoapods usage is kinda transparent to them which is good and bad.

Thanks for dll tip, I'll give that a go and see if that does what I need for now.

**Comment by stewartmiles** [comment]
Ok great, so we'll continue to look at changing the specification of
dependencies to a set of config files.  That should work in your case as
you could rewrite the config file and that would trigger re-resolution.

Cheers,
Stewart

**Comment by stewartmiles** [comment]
@dwxw FYI we've added support for dependencies specified via XML files now and we're looking at moving away from exposing the API for adding dependencies.  Changing the XML files now updates all dependencies without needing to reload the IOSResolver.dll.

**Comment by dwxw** [comment]
Tried out the new xml setup and it works a treat.  I can easily add and remove dependencies.
Cheers,
David.
