### ISSUE TITLE
[Bug]  Linux, no iOS modules installed

### ISSUE THREAD

**Issue by sfjohansson** [googlesamples/unity-jar-resolver#596]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.2.5f1
  * External Dependency Manager version: 1.2.175
  * Source you installed EDM4U: Unity Package Manager
  * Features in External Dependency Manager in use: Android Resolver, iOS Resolver, VersionHandle
  * Plugins SDK in use: Firebase, Admob
  * Platform you are using the Unity editor on: Linux

### [REQUIRED] Please describe the issue here:
When opening a project on Linux, no iOS modules  installed:

```Assembly 'Packages/com.google.external-dependency-manager/ExternalDependencyManager/Editor/1.2.175/Google.IOSResolver.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
```

#### Please answer the following, if applicable:
100% Repro rate

What happened? How can we make the problem occur?
Import the plugin into a project, with no iOS modules loaded, possibly only affecting Linux
My current build target is standalone

**Comment by paulinon** [comment]
Hi @sfjohansson,

Thanks for bringing this to our attention. The error message is returned when you don't have iOS Build Support installed from the Unity Hub. This issue seems similar to #412, so I'll be closing this and marking it as a duplicate, and you may refer to the aforementioned. ticket for updates.
