### ISSUE TITLE
Resolver gets stuck at 24%

### ISSUE THREAD

**Issue by Shady9595** [googlesamples/unity-jar-resolver#631]
* Unity editor version: 2022.3.2f1
  * External Dependency Manager version: 1.2.177
  * Source you installed EDM4U: unityPackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase, MaxSDK, Facebook, Adjust, Google Mobile Ads, Revenue Cat, Game Analytics
  * Platform you are using the Unity editor on: Android

There are no errors popping up but the resolver gets stuck at 24% and does not proceed further. Waited for a whole hour but still it stayed stuck there.

**Comment by paulinon** [comment]
Hi @Shady9595,

Does this behavior occur when you click `Resolve` or `Force Resolve`? If so, could you try if enabling both Custom Main Gradle Template and Custom Gradle Properties Template from your Player Settings > Publishing Settings makes any difference? This can make downloading Android libraries faster.

**Comment by Shady9595** [comment]
This behavior occurs in both cases either I click Resolve or Force Resolve. I also have tried enabling both Custom Main Gradle Template and Custom Gradle Properties Template, after enabling these if I run the resolver it says Resolution Succeeded the moment I click on Resolve or Force Resolve but Libraries aren't created inside Plugins > Android directory.

**Comment by paulinon** [comment]
Hi @Shady9595,

Apologies for the radio silence here. With the Custom Main Gradle Template enabled, the libraries can be found in the generated `mainTemplate.gradle` file. This solution helps prevent duplicate class errors or slow resolution with the libraries in the Plugins > Android directory.

That said, I'll be closing this for now. Let me know if this solution doesn't fit with your use case so that this ticket could be reopened.
