### ISSUE TITLE
[Bug] Android Force Resolve window won't go away

### ISSUE THREAD

**Issue by alex-moonlitgames** [googlesamples/unity-jar-resolver#685]
This is a copy/paste from a bug report on firebase sdk repo, at the request of @argzdev 
[https://github.com/firebase/firebase-unity-sdk/issues/1033
](https://github.com/firebase/firebase-unity-sdk/issues/1033)

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.29f1
  * External Dependency Manager version: 1.2.166
  * Source you installed EDM4U: package manager 11.6.0 (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: android resolver(Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: firebase, facebook (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: windows (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
Today I did a force resolution for android, like I do when making a new release candidate and this newer popup without a close button appeared.

There was a smaller popup that told me that everything is complete, with an OK button, but pressing that OK button did not remove the big one. I had to drag the corners to slightly move it away from blocking me.

Restart / Library delete did not help
![image](https://github.com/googlesamples/unity-jar-resolver/assets/124737077/3760908c-2593-4839-a66d-d94a0b6f1246)

#### Please answer the following, if applicable:
100%

What happened? How can we make the problem occur?
Android Force Resolve

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by a-maurice** [comment]
Since you've been able to reproduce it reliably, can you try turning on verbose logging, in the Android Resolver settings?  I'd assume maybe it is throwing an error that isn't getting handled correctly?

Also, I assume you aren't using a mainTemplate.gradle?  Generally we have found that to be more stable, and newer versions of EDM4U prompt users to switch to that, as it no longer relies on copying all the Android libraries into a local folder, and just uses gradle to handle the dependencies.  So if you are willing to try that, that might help as well.
