### ISSUE TITLE
Please don't mention version number to DLL files in Releases

### ISSUE THREAD

**Issue by voxelbusters** [googlesamples/unity-jar-resolver#69]
Hi,
    This is really a great initiative and almost all plugin developers are happy with your project :)
We really thank Google, @claywilkinson, @stewartmiles and his team for making this happen.

Regarding the issue, please don't have the version numbers for the dll's in the release versions. This makes it difficult as there are errors on importing different plugin publishers copy.

We think its better not to include the version number to dll files. Please suggest.

Thanks,
VB Team

![multidllissue_jarresolver](https://user-images.githubusercontent.com/11584944/30742785-633626cc-9fb8-11e7-9694-9862f2bfb63e.jpg)

**Comment by stewartmiles** [comment]
Just to make sure @voxelbusters you closed this because you noticed why we do this here https://github.com/googlesamples/unity-jar-resolver#version-handler ?

I have some ideas on how to improve this further at the cost of making plugins a little more opaque (e.g shipping a versioned zip file rather than separate files that each have to be versioned) per plugin.  This would further reduce the loading / reloading and work on handling multiply versioned transitive dependencies.  It's all about time though, we have very little to work on this :)

**Comment by voxelbusters** [comment]
Thanks @stewartmiles  for the followback :)
Actually I closed the issue seeing the issue didn't happen. But now i see its happening again.
On importing a new version it made duplicate class warnings.

If you don't mind, Can you please explain more on Version Handler?

**Comment by voxelbusters** [comment]
Thanks @stewartmiles for the followback :)
Actually I closed the issue seeing the issue didn't happen. What I found out was I disabled Version Management.
If you don't mind, Can you please explain more on Version Handler?
