### ISSUE TITLE
Problem Occur when I click Resolve Client Jars

### ISSUE THREAD

**Issue by kenglou** [googlesamples/unity-jar-resolver#75]
I'm using Unity3d 5.6.3p4 with Google Play Game Service Unity Plugin 0.9.40 and Gradle Experimental Enabled. When I press on Resolve Client Jars message below Occurs:

```
InvalidCastException: Cannot cast from source type to destination type.
GooglePlayServices.UnityCompat.GetAndroidBuildToolsVersion ()
GooglePlayServices.GradlePreBuildResolver.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.MenuResolve ()
```

May i know what happens?

**Comment by johnb003** [comment]
This was a really old version of the plugin. It probably was packaged with an old version of Google Play Games Services. Please install the latest Unity Jar Resolver from github.

This was fixed in:
https://github.com/googlesamples/unity-jar-resolver/commit/23d03a06798ae62c5b9aadafd45d1c407c5abe4d

* UnityCompat reflection methods 'GetAndroidPlatform' and
  'GetAndroidBuildToolsVersion' are now Obsolete due to dependence on the
  obsolete 'android' build tool.

This broke when the Android team dropped support for the "android" tool that Unity used to determine the versions of build tools and platform version.  The fix was made Aug 15th, and "GetAndroidBuildToolsVersion" has been deprecated since.
