### ISSUE TITLE
The new settings xml doesn't work with Perforce

### ISSUE THREAD

**Issue by tommikiviniemi-srs** [googlesamples/unity-jar-resolver#79]
Hi,

I noticed that one of the more recent updates to the resolver introduced an alternative way of saving the settings, using an xml file in project settings instead of editor preferences.

This will not work with Perforce as it requires files to be checked out before writing to, thus it will fail when trying to write to a read protected file. We'd rather use the editor preferences anyway but I couldn't find any meaningful access to the settings "mode" so I resorted to an [InitializeOnLoad] class that does the following:

		EditorPrefs.SetInt("Google.VersionHandler.UseProjectSettings", 0);
		EditorPrefs.SetInt("GooglePlayServices.UseProjectSettings", 0);
		EditorPrefs.SetInt("Google.IOSResolver.UseProjectSettings", 0); // this doesn't use project settings but added here in case it adapts to it in the future

Is this the proper way of handling this, as it seems a bit hackish to me? Or could you maybe add proper Perforce support to cover this case? Here's a sample class for adding support for Perforce:

public static class EditorUtils {
	public static UnityEditor.VersionControl.Asset CheckOut(string path) {
		if (!EditorUtils.ShouldUseVersionControl())
			return null;

		UnityEditor.VersionControl.Task task = UnityEditor.VersionControl.Provider.Checkout(path, UnityEditor.VersionControl.CheckoutMode.Both);
		task.Wait();
		return UnityEditor.VersionControl.Provider.GetAssetByPath(path);
	}

	public static void Revert(UnityEditor.VersionControl.Asset asset, UnityEditor.VersionControl.RevertMode revertMode = UnityEditor.VersionControl.RevertMode.Unchanged) {
		if (!EditorUtils.ShouldUseVersionControl())
			return;

		UnityEditor.VersionControl.Task task = UnityEditor.VersionControl.Provider.Revert(asset, revertMode);
		task.Wait();
	}

	public static bool ShouldUseVersionControl() {
		return UnityEditor.VersionControl.Provider.enabled &&
			UnityEditor.VersionControl.Provider.isActive &&
			(!UnityEditor.VersionControl.Provider.requiresNetwork || UnityEditor.VersionControl.Provider.onlineState == UnityEditor.VersionControl.OnlineState.Online);
	}
}

Thanks!

**Comment by stewartmiles** [comment]
Hi @tommikiviniemi-srs ,

We added project level settings by default as a lot of users want to configure at a project level rather than for the entire application.  This is especially important for continuous integration where folks build multiple projects on a single server each with their own settings.

You're right though, we forgot about Perforce with it's real-only files :).

If I'm reading your code snippet correctly, it sounds like you want to see everything under ProjectSettings wrapped in version code handling automatically.

There are a couple of places where we attempt to write to settings that we would need wrap in this logic:

https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/src/PlayServicesResolver.cs#L88
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/VersionHandlerImpl/src/ProjectSettings.cs#L358

Is that right?

**Comment by stewartmiles** [comment]
Actually, thinking about this a bit more .. since Android Resolution dumps a set of assets in your project and can potentially delete / change things as well it sounds like all of that code should end up going through version control logic.  Sounds like a pretty big change.  Why would wrapping writing files to ProjectSettings be ok for you and not changing other assets in the project e.g files under Assets/Plugins/Android ?

**Comment by tommikiviniemi-srs** [comment]
Hi Stewart!

I absolutely think it's great being able to serialise the settings for an entire team or for different environments, we actually created a class that forcefully set certain parameters at boot to unify settings for everyone on the teams and we dynamically alter them at build time, as a workaround for when this functionality didn't exist. We'd like to adopt the new serialized format but the write protection is preventing us from doing it atm.

Regarding write protection of the plugins folders - that's a controlled action done by programmers (in that they run the resolvers to update the project when there is QA time scheduled for it and a specific need to update), and they know to check out the entire plugins folder first. However, having a UI dialog where pressing buttons starts throwing exceptions is not a great user experience as we may need to instruct certain people to toggle certain settings depending on what they are doing. It's more about the audience of the feature, a generic looking UI throwing exceptions, or a feature only programmers should access. It's not even that bad having the extra line of defence to prevent anyone from accidentally running the resolvers as the files are write protected. Of course with time it'd be preferable if everything worked without "lore", but the fact that the UI doesn't check out the appropriate settings files prevents us from moving towards the new xml format is something I wanted to react to, especially if you at some point decide to deprecate the old editor settings based model.

Thanks again,
- Tommi

**Comment by stewartmiles** [comment]
@tommikiviniemi-srs totally agree about the settings thing, I've put together a patch but need to put together a local p4 setup to test it out which could take a little while.  In the prototype I've hacked up if the settings file(s) can't be checked out due to SCM being offline / disabled, the ProjectSettings class will report an error and ignore the changes.  It's not great but at least it should prevent it from throwing exceptions.

I am still a little confused about plugins that modify the project structure.  If a developer runs the Android Resolver - which adds / removes files from the plugins directory - then it would probably be nice to have SCM integration in that case as well.  I guess once we get a p4 setup in place we can give it a try to see what else needs to be fixed here.

**Comment by JimmyDeemo** [comment]
Don't suppose this is any closer to getting looked at? This caused a problem for me with settings not being serialised and breaking the build machine (resolve on build happened when it wasn't supposed to).

**Comment by stewartmiles** [comment]
@JimmyDeemo it's not being looked at by anyone at the moment.  If you want to send a pull request it would be appreciated.

**Comment by JimmyDeemo** [comment]
I made a pull request. #256

**Comment by stewartmiles** [comment]
This was fixed a while ago by https://github.com/googlesamples/unity-jar-resolver/pull/256 thanks @JimmyDeemo
