### ISSUE TITLE
Optional ${applicationId} replace

### ISSUE THREAD

**Issue by Gasparfx** [googlesamples/unity-jar-resolver#93]
Hi!
Can you make replacing ${applicationId} with package name optional? Unity deals with ${applicationId} in aar and ant libraries now.

We have multiple version of our game with different package names. So hard-coded package name is not suitable. I changed it back to ${applicationId} in all xml files and now it works good. But when i hit "Resolve" it change it to hard code again.

**Comment by stewartmiles** [comment]
Hi @Gasparfx which version of Unity do they introduce support for applicationId?  It would be nice to follow the correct behavior based upon the version.

BTW You should be able to disable AAR explosion - and therefore replacement of applicationId - by turning off the "Explode AARs" setting.

Cheers,
Stewart

**Comment by Gasparfx** [comment]
> BTW You should be able to disable AAR explosion - and therefore replacement of applicationId - by turning off the "Explode AARs" setting.
I did that, but it doesn't work for Android Libraries(like firebase).

> which version of Unity do they introduce support for applicationId?
I am not sure about version number, but it looks like Unity support this since they start use manifestmerger utility from android sdk. Unity 5.5 has this in docs:
https://docs.unity3d.com/550/Documentation/Manual/android-manifest.html
But i tried only in 2017.2.

**Comment by Gasparfx** [comment]
Looks like there were bugs with merger:
https://issuetracker.unity3d.com/issues/android-applicationid-is-not-being-provided-in-the-build-dot-gradle
So i am not sure about Unity 5.5

**Comment by Jyri-K** [comment]
Hi. We're using the version 1.2.84 with Unity 2017.4.8f1 and it seems like disabling "Explode AARs" is not working. We still get _"Will apply attribute value replacements: ${applicationId} --> com.mygame.bundle"_ in at least Firebase and Facebook SDKs.

**Comment by stewartmiles** [comment]
@Jyri-K there is a bug in Unity which doesn't correctly apply variable replacement in any custom `AndroidManifest.xml` files in addition to - in some versions - `AndroidManifest.xml` files in AARs.  I'm cool with having an option to disable this but I'm not going to go through every version of Unity to validate that it works correctly in all scenarios any time soon.  If you feel strongly about it, we would happily accept a pull request with a log of tests across each Unity version.

**Comment by Jyri-K** [comment]
Ok, I'm a bit confused and I'm sorry if I've understood the Jar Resolver behavior incorrectly. Like Gasparfx above, we also have same project that has different builds with different bundle ids. I understand this is special case. 

Anyway this is what happens with our project in Unity:

1. Bundle id is old.game.bundle -> Press 'Android/Force resolve'
2. Android/Plugins folder contents is cleared, then necessary .aar files are downloaded
3. On certain .aar files we see Unity log message:

"Will apply attribute value replacements: ${applicationId} --> old.game.bundle"
Files that cause this are for example:
com.google.games.gpgs-plugin-support-0.9.50.aar
com.google.signin.google-signin-support-1.0.3.aar
com.facebook.android.facebook-marketing-4.35.0.aar

4. The process is done.

5. Now if I change the bundle id to new.game.bundle -> Get Unity log message:
"Bundle ID changed: old.game.bundle --> new.game.bundle"

6. This triggers steps 1-4 again automatically

It's a bit time consuming since basically Jar Resolver is downloading the same files again.

Is there a way to prevent this? What we are hoping is to make the ${applicationId} stay intact in the sdk files and perform that step 3 replacement only when we actually build the .apk file?

Is this the Unity bug you mentioned or is this some incorrect setting we have in Jar Resolver settings?

**Comment by stewartmiles** [comment]
@Jyri-K the bug is in Unity's manifest merger which is why resolution has to occur again.  It is a little odd that it's downloading everything again, it just uses gradle for dependency resolution and download of artifacts via the now huge script https://github.com/googlesamples/unity-jar-resolver/blob/master/source/PlayServicesResolver/scripts/download_artifacts.gradle .  Gradle should be caching everything it downloads to a directory on your filesystem, so perhaps something is going wrong with the way we have it configured?

**Comment by stewartmiles** [comment]
Support for optional replacement was added back in June fa3a22a37d3dc50ffcd31e0c20b338ce9a250227 .  I guess I forgot that we have a setting to disable patching of AndroidManifest.xml .
